services:
  postgres:
    container_name: dev-postgres
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev-postgres:/var/lib/postgresql/data/
      # - ~/dump.sql:/docker-entrypoint-initdb.d/dump.sql # TIP: restore backup

  redis:
    container_name: dev-redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  clickhouse:
    container_name: dev-clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123 # HTTP interface
      - 9000:9000 # Native client interface
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - dev-clickhouse:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  dev-postgres:
  dev-clickhouse:
